### ISSUE TITLE
LULU postclustering step error

### ISSUE THREAD

**Issue by slambrechts** [pipecraft2/pipecraft#4]
Hi,

When running LULU in pipecraft2, pipecraft stops and reports 'ERROR]:' without any additional information. When I look at the `R_run.log` in the `lulu_out` output folder it says:

`Error in library(devtools) : there is no package called 'devtools' Execution halted
`

Can I install devtools myself, or does the pipecraft LULU docker image needs to be updated (fyi I'm using Pipecraft_v0.1.4)?

Kind regards,
Sam

**Comment by METS0JA** [comment]
Hi, could you please provide a couple extra details such as which OS are you using and if on MacOS of are you supporting an intel chip or a M1/M2 chip ?

**Comment by slambrechts** [comment]
Hi, 

Thank you for your reply! We are using Pipecraft on Windows 11 Enterprise (22H2) with an intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.60 GHz (64 bit).

Regarding the error message, there were no extra details except for the ones posted above. In the `lulu_out `output folder I have the following files:

![image](https://github.com/pipecraft2/pipecraft/assets/29545120/532f0229-44b2-4841-99c7-1928f5da0515)

**Comment by slambrechts** [comment]
When trying to run LULU manually on the same computer, it also didn't work due to devtools. When trying to run LULU manually on a different pc, it did however work, so I think this was not a Pipecraft problem
